version: '3.8'

services:
  task-management-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: task-management-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
